# Generated by Django 4.0 on 2023-08-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
